#!/usr/bin/env bash
# installs nginx web server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i 's/listen       80;/listen       80 default_server;/g' /etc/nginx/sites-available/default
service nginx restart
