#!/usr/bin/env bash
# installs nginx web server
apt-get -y update
apt-get -y install nginx
sudo sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
