#!/usr/bin/env bash
# create a new user for the replica server
# The name of the new user should be replica_user, with the host name set to %, and can have whatever password you’d like
# replica_user must have the appropriate permissions to replicate your primary MySQL server
# holberton_user will need SELECT privileges on the mysql.user table in order to check that replica_user was created with the correct permissions
sudo mysql -u root -p -e "CREATE USER 'replica_user'@'%' IDENTIFIED BY 'password'; GRANT REPLICATION SLAVE ON *.* TO 'replica_user'@'%';" -h localhost
sudo mysql -u root -p -e "GRANT SELECT ON mysql.user TO 'holberton_user'@'localhost';" -h localhost
