#!/usr/bin/env bash
# Create a database named tyrell_corp.
# Within the tyrell_corp database create a table named nexus6 and add at least one entry to it.
# Make sure that holberton_user has SELECT permissions on your table so that we can check that the table exists and is not empty.
sudo mysql -u root -p -e "CREATE DATABASE tyrell_corp; USE tyrell_corp; CREATE TABLE nexus6 (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255)); INSERT INTO nexus6 (name) VALUES ('entry1'); GRANT SELECT ON tyrell_corp.nexus6 TO 'holberton_user'@'localhost';" -h localhost 
